# Generated by Django 3.0.7 on 2020-08-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qas_app', '0002_question_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='person',
        ),
    ]
