# Generated by Django 3.0.7 on 2020-08-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qas_app', '0004_question_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='person',
            new_name='author',
        ),
    ]
