# Generated by Django 3.0.7 on 2021-04-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qas_app', '0008_auto_20210411_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_answered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
